name: admin_panel
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # SVG
  flutter_svg: ^2.0.6

  # iOS style icons.
  cupertino_icons: ^1.0.2

  # Code generation for assets
  flutter_gen: ^5.3.1

  # BLoC
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # routing
  go_router: ^14.2.0

  # logger
  l: ^4.0.2
  
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  dio: ^5.3.4
  image_picker: ^1.0.4
  sqflite: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path: ^1.9.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.0
  firebase_storage: ^10.2.0
  fl_chart: ^0.68.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
flutter_gen:
  output: lib/src/gen
  integrations:
    flutter_svg: true
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  
  fonts:
    - family: Righteous
      fonts:
        - asset:  assets/fonts/Righteous-Regular.ttf
  